"""Unified entry point for live cameras and local video processing."""

import argparse
import os
import signal
import sys
import time
from pathlib import Path
from queue import Queue


sys.path.insert(0, str(os.getcwd()))
if str(os.getcwd()) != "/home/pi/NanoPi-R6S-ALPCMR":
    sys.path.insert(0, str(os.getcwd()) + "/NanoPi-R6S-ALPCMR")

from src.camera.camera_config import (
    CameraConfigError,
    load_camera_endpoints,
    redact_rtsp_url,
)
from src.camera.read_cam import Camera, StreamWS
from src.run import GracefulKiller, RunWorker


# ---------------------------------------------------------------------------
# MODE SWITCH: keep exactly ONE of the following three lines uncommented.
# ---------------------------------------------------------------------------
# RUN_MODE = "video"
# RUN_MODE = "camera"
RUN_MODE = "usb"


VIDEO_PATH = "/home/pi/lp/3.mp4"

# Stable UVC path based on the USB camera serial number. Unlike /dev/video0,
# this path remains tied to the same physical camera across reboots.
USB_CAMERA_DEVICE = (
    "/dev/v4l/by-id/"
    "usb-Xitech_USB_Camera_20250606105-video-index0"
)
USB_CAMERA_WIDTH = 2592
USB_CAMERA_HEIGHT = 1944
USB_CAMERA_FPS = 30

# These legacy URLs are temporary fallbacks for a safe staged migration. Once
# runtime configuration has been verified on both camera ports, credentials
# will be removed from this file.
FRONT_CAMERA_URL = "rtsp://admin:123456@192.168.168.52:554/stream1"
REAR_CAMERA_URL = "rtsp://admin:123456@192.168.59.227:554/stream1"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CAMERA_CONFIG_PATH = PROJECT_ROOT / "config" / "cameras.json"
CAMERA_SECRETS_PATH = (
    Path.home() / ".config" / "nanopi-alpr" / "camera_secrets.env"
)

FRONT_STREAM_PORT = 8765
REAR_STREAM_PORT = 8766

# Keep the existing dashboard bandwidth for LAN/video modes. USB mode is set
# to 1.0 so the browser receives the full 5MP USB frame.
DEFAULT_WEB_STREAM_SCALE = 0.33
USB_WEB_STREAM_SCALE = 1.0
WEB_STREAM_JPEG_QUALITY = 50


def parse_args():
    """Allow optional command-line overrides without requiring autoLP changes."""
    parser = argparse.ArgumentParser(description="LP detection program")
    parser.add_argument(
        "--mode",
        choices=("video", "camera", "usb"),
        default=RUN_MODE,
        help="Input mode; defaults to RUN_MODE at the top of this file.",
    )
    parser.add_argument("--video", default=VIDEO_PATH, help="Local video path.")
    parser.add_argument(
        "--usb-device",
        default=USB_CAMERA_DEVICE,
        help="Stable V4L2 capture device used in USB mode.",
    )
    parser.add_argument("--usb-width", type=int, default=USB_CAMERA_WIDTH)
    parser.add_argument("--usb-height", type=int, default=USB_CAMERA_HEIGHT)
    parser.add_argument("--usb-fps", type=int, default=USB_CAMERA_FPS)
    parser.add_argument(
        "--source1",
        help="Explicit front RTSP URL; overrides runtime camera configuration.",
    )
    parser.add_argument(
        "--source2",
        help="Explicit rear RTSP URL; overrides runtime camera configuration.",
    )
    parser.add_argument(
        "--camera-config",
        default=str(CAMERA_CONFIG_PATH),
        help="Runtime camera JSON generated by camera_manager.py.",
    )
    parser.add_argument(
        "--camera-secrets",
        default=str(CAMERA_SECRETS_PATH),
        help="Private camera credentials file; must have mode 600.",
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Run without terminal input; intended for systemd.",
    )
    return parser, parser.parse_args()


def resolve_camera_sources(args):
    """Resolve CLI, runtime-config, and legacy camera sources in that order."""
    front_source = FRONT_CAMERA_URL
    rear_source = REAR_CAMERA_URL
    front_origin = "legacy fallback"
    rear_origin = "legacy fallback"

    try:
        endpoints = load_camera_endpoints(
            args.camera_config,
            args.camera_secrets,
        )
    except CameraConfigError as exc:
        print(f"[CameraConfig] Runtime config unavailable: {exc}")
        print("[CameraConfig] Using legacy camera URL fallback")
    else:
        front_endpoint = endpoints.get("front")
        if front_endpoint is not None:
            front_source = front_endpoint.rtsp_url
            front_origin = f"runtime config ({front_endpoint.interface})"

        rear_endpoint = endpoints.get("rear")
        if rear_endpoint is not None:
            rear_source = rear_endpoint.rtsp_url
            rear_origin = f"runtime config ({rear_endpoint.interface})"

    if args.source1:
        front_source = args.source1
        front_origin = "command line"
    if args.source2:
        rear_source = args.source2
        rear_origin = "command line"

    return front_source, rear_source, front_origin, rear_origin


def main():
    parser, args = parse_args()

    front_width = 1920
    front_height = 1080
    front_fps = 30
    front_web_stream_scale = DEFAULT_WEB_STREAM_SCALE

    if args.mode == "video":
        if not os.path.isfile(args.video):
            parser.error(f"Video file not found: {args.video}")
        front_source = args.video
        rear_source = None
        frame_queue_size = 1
        print(f"[Main] Mode: VIDEO ({front_source})")
        print("[Main] Processing and streaming front input only")
    elif args.mode == "usb":
        if args.usb_width <= 0 or args.usb_height <= 0 or args.usb_fps <= 0:
            parser.error("USB width, height, and FPS must be positive")
        if not os.path.exists(args.usb_device):
            parser.error(f"USB camera device not found: {args.usb_device}")

        front_source = args.usb_device
        rear_source = None
        front_width = args.usb_width
        front_height = args.usb_height
        front_fps = args.usb_fps
        front_web_stream_scale = USB_WEB_STREAM_SCALE

        # Preserve the original live-camera processing queue behavior. The
        # browser queue remains independently limited to one latest frame.
        frame_queue_size = 10
        print("[Main] Mode: USB CAMERA (front input only)")
        print(f"[Main] USB device: {front_source}")
        print(
            f"[Main] USB capture: "
            f"{front_width}x{front_height}@{front_fps}"
        )
        print(
            f"[Main] USB web stream: "
            f"{front_width}x{front_height} "
            f"(scale={front_web_stream_scale}, "
            f"JPEG quality={WEB_STREAM_JPEG_QUALITY})"
        )
        print("[Main] Models and front WebSocket stream are active")
    else:
        (
            front_source,
            rear_source,
            front_origin,
            rear_origin,
        ) = resolve_camera_sources(args)
        frame_queue_size = 10
        print("[Main] Mode: CAMERA (front + rear RTSP)")
        print(
            f"[Main] Front camera [{front_origin}]: "
            f"{redact_rtsp_url(front_source)}"
        )
        print(
            f"[Main] Rear camera [{rear_origin}]: "
            f"{redact_rtsp_url(rear_source)}"
        )

    killer = GracefulKiller()

    # Model queues and browser queues are independent. Stream queues stay at
    # one frame so the dashboard always displays the newest available image.
    front_frame_queue = Queue(maxsize=frame_queue_size)
    rear_frame_queue = Queue(maxsize=frame_queue_size)
    stream_front_queue = Queue(maxsize=1)
    stream_rear_queue = Queue(maxsize=1)
    result_queue = Queue(maxsize=10)

    front_camera = Camera(
        front_frame_queue,
        stream_front_queue,
        front_source,
        killer,
        "F",
        width=front_width,
        height=front_height,
        fps=front_fps,
    )
    front_stream = StreamWS(
        killer,
        "0.0.0.0",
        FRONT_STREAM_PORT,
        stream_front_queue,
        scale=front_web_stream_scale,
        jpeg_quality=WEB_STREAM_JPEG_QUALITY,
    )

    rear_camera = None
    rear_stream = None
    if rear_source is not None:
        rear_camera = Camera(
            rear_frame_queue,
            stream_rear_queue,
            rear_source,
            killer,
            "R",
        )
        rear_stream = StreamWS(
            killer,
            "0.0.0.0",
            REAR_STREAM_PORT,
            stream_rear_queue,
        )

    run_worker = RunWorker(
        front_frame_queue,
        rear_frame_queue,
        result_queue,
        killer,
    )

    if args.headless:
        def request_stop(signum, _frame):
            print(f"[Main] Received signal {signum}; stopping")
            killer.stop()

        signal.signal(signal.SIGTERM, request_stop)
        signal.signal(signal.SIGINT, request_stop)

    try:
        run_worker.run()
        front_camera.start()
        if rear_camera is not None:
            rear_camera.start()

        front_stream.run()
        if rear_stream is not None:
            rear_stream.run()

        if args.headless:
            print("[Main] Headless mode active")
            while not killer.is_stopped():
                time.sleep(0.5)
        else:
            input("[Main] Press Enter to stop...\n")
    except KeyboardInterrupt:
        print("\n[Main] Stop requested")
    finally:
        front_camera.stop()
        if rear_camera is not None:
            rear_camera.stop()
        killer.stop()
        run_worker.stop()

    print("[Main] Done.")


if __name__ == "__main__":
    main()